### ISSUE TITLE
(.so) libraries for Android support

### ISSUE THREAD

**Issue by YevhenRozhovetskyi** [helpsterTee/Unity-IFCEngine#11]
We are going to use your plugin for Android, but it doesn't work with (.dll) files.  
Could you build (.so) libraries for Android support?

Thank you so much.

**Comment by helpsterTee** [comment]
I guess that won't work due to the dependency on IfcEngine. While they have linux binaries, the Android system differs to a certain extend. Also file choosing would be different, so this needs a fork.

Do you need a standalone solution or is server-client okay? Then maybe look into https://github.com/helpsterTee/XBivine-Unity and https://github.com/helpsterTee/XBivine
XBivine does not have external dependencies on anything, except the server part, where it shouldn't matter for Android.

**Comment by helpsterTee** [comment]
Closed due to inactivity.
